{"name": "test_minus_2[5-5-1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 1\n +  where 0 = <bound method Sub.minus of <src.operations.minus.sub.Sub object at 0x7f8194222050>>(5, 5)\n +    where <bound method Sub.minus of <src.operations.minus.sub.Sub object at 0x7f8194222050>> = <src.operations.minus.sub.Sub object at 0x7f8194222050>.minus", "trace": "self = <src.operations.minus.tests.test_sub_2.TestSub2 object at 0x7f81942229b0>, num1 = 5, num2 = 5, result = 1\n\n    @pytest.mark.parametrize(\"num1, num2, result\",\n        [\n            (6, 5, 1),\n            (5, 5, 1),\n            (4, 5, -1),\n            (2, 2, 0)\n        ]\n    )\n    def test_minus_2(self, num1, num2, result):\n>       assert sub_operation.minus(num1, num2) == result\nE       assert 0 == 1\nE        +  where 0 = <bound method Sub.minus of <src.operations.minus.sub.Sub object at 0x7f8194222050>>(5, 5)\nE        +    where <bound method Sub.minus of <src.operations.minus.sub.Sub object at 0x7f8194222050>> = <src.operations.minus.sub.Sub object at 0x7f8194222050>.minus\n\noperations/minus/tests/test_sub_2.py:17: AssertionError"}, "parameters": [{"name": "num1", "value": "5"}, {"name": "num2", "value": "5"}, {"name": "result", "value": "1"}], "start": 1678287317519, "stop": 1678287317521, "uuid": "a0b2a449-2590-45be-a568-64ffdcd3054a", "historyId": "60df6b998f2eba6b960cb981500e60f1", "testCaseId": "663308db3b5eaf58747a38322088272e", "fullName": "operations.minus.tests.test_sub_2.TestSub2#test_minus_2", "labels": [{"name": "parentSuite", "value": "operations.minus.tests"}, {"name": "suite", "value": "test_sub_2"}, {"name": "subSuite", "value": "TestSub2"}, {"name": "host", "value": "npalleta-Avell-G1555-MUV-A62-MUV"}, {"name": "thread", "value": "45103-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "operations.minus.tests.test_sub_2"}]}